# -- 코드를 입력하세요
# SELECT t4.AUTHOR_ID,
#        t4.AUTHOR_NAME,
#        t4.CATEGORY,
#        SUM(t3.SALES * t4.PRICE) AS SALES
# FROM BOOK_SALES t3
# INNER JOIN (
#     SELECT t1.BOOK_ID,
#            t1.AUTHOR_ID,
#            t2.AUTHOR_NAME,
#            t1.CATEGORY,
#            t1.PRICE
#     FROM BOOK t1
#     LEFT JOIN AUTHOR t2 ON t1.AUTHOR_ID = t2.AUTHOR_ID
#     WHERE YEAR(t1.PUBLISHED_DATE) = 2022
#       AND MONTH(t1.PUBLISHED_DATE) = 1
# ) AS t4 ON t3.BOOK_ID = t4.BOOK_ID
# GROUP BY t4.AUTHOR_ID, t4.AUTHOR_NAME, t4.CATEGORY;

# SELECT t1.BOOK_ID,
#            t1.AUTHOR_ID,
#            t2.AUTHOR_NAME,
#            t1.CATEGORY,
#            t1.PRICE

# WHERE YEAR(t1.PUBLISHED_DATE) = 2022
#   AND MONTH(t1.PUBLISHED_DATE) = 1

SELECT t12.AUTHOR_ID,
        t12.AUTHOR_NAME,
        t12.CATEGORY,
        SUM(t3.SALES * t12.PRICE) as 'SALES'
    FROM BOOK_SALES as t3
    LEFT JOIN (SELECT t1.BOOK_ID, t1.CATEGORY, t1.AUTHOR_ID, t1.PRICE, t1.PUBLISHED_DATE, t2.AUTHOR_NAME
                FROM BOOK as t1
                LEFT JOIN AUTHOR as t2 ON t1.AUTHOR_ID = t2.AUTHOR_ID) as t12
    ON t3.BOOK_ID = t12.BOOK_ID
    WHERE YEAR(t3.SALES_DATE) = 2022 AND MONTH(t3.SALES_DATE) = 1
    GROUP BY t12.AUTHOR_ID, t12.CATEGORY
    ORDER BY t12.AUTHOR_ID, t12.CATEGORY DESC
    