-- 코드를 입력하세요
SELECT t1.PRODUCT_CODE,
        sum(t2.SALES_AMOUNT)* t1.PRICE as 'SALES'
    FROM PRODUCT as t1
    INNER JOIN OFFLINE_SALE as t2
    ON t1.PRODUCT_ID = t2.PRODUCT_ID
    GROUP BY t2.PRODUCT_ID
    ORDER BY SALES Desc, t1.PRODUCT_CODE