# -- 코드를 입력하세요
# SELECT t1.PRODUCT_ID,
#     t1.PRODUCT_NAME,
#     t1.price * t2.amount as TOTAL_SALES
#     FROM FOOD_PRODUCT as t1
#     INNER JOIN FOOD_ORDER as t2
#     ON t1.PRODUCT_ID = t2.PRODUCT_ID
#     GROUP BY t1.PRODUCT_NAME
#     WHERE YEAR(PRODUCE_DATE) = 2022 and MONTH(PRODUCE_DATE) = 5
#     ORDER BY TOTAL_SALES DESC, t1.PRODUCT_ID

SELECT t1.PRODUCT_ID,
    t1.PRODUCT_NAME,
    SUM(t1.price * t2.amount) as TOTAL_SALES
    FROM FOOD_PRODUCT as t1
    INNER JOIN FOOD_ORDER as t2
    ON t1.PRODUCT_ID = t2.PRODUCT_ID
    WHERE YEAR(PRODUCE_DATE) = 2022 and MONTH(PRODUCE_DATE) = 5
    GROUP BY t1.PRODUCT_NAME
    ORDER BY TOTAL_SALES DESC, t1.PRODUCT_ID