-- 코드를 입력하세요
SELECT t1.FLAVOR
    FROM FIRST_HALF as t1
    RIGHT JOIN (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER  FROM JULY GROUP BY FLAVOR) as t2
    ON t1.SHIPMENT_ID = t2.SHIPMENT_ID
    ORDER BY t1.TOTAL_ORDER + t2.TOTAL_ORDER DESC
    LIMIT 3

# SELECT *
#     FROM FIRST_HALF